site_name: Enterprise Data Platform
site_description: Technical documentation
copyright: "© 2025 Selenite®  |  Selenite Business Solutions Pvt. Ltd. All rights reserved."

theme:
  name: material
  logo: assets/logos/bare_count_logo_dark.svg  # Logo in the light scheme
  favicon: assets/logos/bare_count_favicon.png
  features:
    - navigation.instant          # Client-side nav for faster page transitions
    - navigation.tracking         # Update URL anchor as you scroll
    - navigation.tabs             # Top-level sections as tabs
    - navigation.tabs.sticky      # Tabs remain visible on scroll
    - toc.follow                  # Auto-highlight current heading in TOC
    - navigation.top              # “Back to top” button
    - navigation.indexes          # Section landing pages
    - navigation.prune            # Hide empty nav items
    - content.code.copy           # Copy button on code blocks
    - content.action.edit         # “Edit this page” action
    - content.tooltips            # Tooltips via title attributes
    - content.tabs.link           # Linked content tabs across pages
    - search.highlight            # Highlight search matches
    - search.suggest              # Search suggestions

extra:
    generator: false              # drop meta “Made with MkDocs”

markdown_extensions:
  - admonition                     # Callout blocks: note/warning/tip/etc.
  - def_list                       # Definition lists: term + definition syntax
  - footnotes                      # In-page footnotes with backlinks
  - attr_list                      # `{}` attribute lists on elements (ids, classes)
  - md_in_html                     # Allow Markdown inside raw HTML blocks
  - toc:                           # Table of contents
      permalink: false             # Add an anchor link to headings
      toc_depth: 2                 # Limit TOC depth (H2+)
  - pymdownx.details               # `<details>` collapsible sections via `???`
  - pymdownx.superfences:          # Fenced code block superpowers + custom fences
      custom_fences:
        - name: mermaid            # ```mermaid
          class: mermaid           #   graph TD; A-->B
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:            # Pygments-based code highlighting
      linenums: false              # Show line numbers on code blocks
      anchor_linenums: true        # Make line numbers linkable
  - pymdownx.inlinehilite          # `==inline code==` highlighting shorthand
  - pymdownx.tabbed:               # Content tabs: ```tab=Foo
      alternate_style: true        # Use alt styling that fits Material nicely
  - pymdownx.tasklist:             # [ ] and [x] task lists
      custom_checkbox: true        # Styled checkboxes
      clickable_checkbox: true     # Toggle checkboxes in the browser
  - pymdownx.critic                # Critic markup (add/del/sub comments) for reviews
  - pymdownx.smartsymbols          # Converts (c), (tm), --, ... into proper glyphs
  - pymdownx.emoji:                # :emoji: support using Material’s SVG set
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:             # Reuse content via !INCLUDE or snippet syntax
      base_path: docs              # Root path for included snippets
  - pymdownx.magiclink             # Auto-link bare URLs and @user/#issue patterns
  - pymdownx.betterem              # Smarter emphasis handling (edge-case fixes)
  - pymdownx.caret                 # ^^insertions^^ (caret markup)
  - pymdownx.mark                  # ==highlights== (mark markup)
  - pymdownx.tilde                 # ~~subscripts~~ and ~~deletions~~ (tilde markup)

plugins:
  - search                         # Built-in search index
  - minify:                        # Reduce HTML size
      minify_html: true
  - redirects                      # Maintain old → new URL mappings
  - awesome-pages                  # Folder-based nav ordering via .pages files

nav:
    - Home:
        - Index: index.md

    - The Platform:

        - About Platform:
            - Index: about-platform/index.md
            - Problem: about-platform/01-problem.md
            - Root Causes: about-platform/02-root-causes.md
            - Solution: about-platform/03-solution.md
            - Offerings: about-platform/04-offerings.md
            - Deployment: about-platform/05-deployment.md

        - Platform User Stories:
            - Index: user-stories/index.md
            - User Roles: user-stories/user-roles.md

            - Setting up Platform:
                - Infra Deployment: user-stories/00a-platform-infrastructure-deployment.md
                - Connector Deployment: user-stories/00b-connector-deployment.md
                - Schema Seeding: user-stories/00c-schema-templates-seeding.md
                - Access Baseline: user-stories/00d-access-rbac-baseline.md

            - Managing Tenant:
                - Tenant Provisioning: user-stories/01-tenant-provisioning.md
                - Tenant Infrastructure Provisioning: user-stories/01b-tenant-infrastructure-provisioning.md
                - Tenant Decommissioning / Offboarding: user-stories/01c-tenant-decommissioning.md

            - Onboarding Data:
                - Data Source Onboarding: user-stories/02-source-onboarding.md
                - Connector Handshake & Preflight: user-stories/02b-connector-handshake-preflight.md

            - Governance:
                - Setting Up Guardrails: user-stories/04-guardrails-dqc.md
                - Evidence: user-stories/05-evidence-lineage.md
                - Automated Housekeeping & Cost Controls: user-stories/05b-housekeeping-cost-controls.md

            - Managing Schemas:
                - Source (Raw) Schema Lifecycle: user-stories/03a-raw-schema-lifecycle.md
                - GDP Schema Lifecycle: user-stories/03b-gdp-schema-lifecycle.md
                - KPI Schema Lifecycle: user-stories/03c-kpi-schema-lifecycle.md
                - Tenant Schema Change Request: user-stories/03d-tenant-schema-change-request.md
                - Tenant-Specific Schema Extension: user-stories/03e-tenant-specific-schema-extension.md
                - Safe Rollout & Rollback: user-stories/03f-safe-rollout-rollback.md
                - Impact Analysis & Notifications: user-stories/03g-impact-analysis-notifications.md

            - KPI Lifecycle:
                - KPI Publishing: user-stories/06-kpi-publishing.md
                - KPI Consumption: user-stories/07-kpi-consumption.md

            - Data Action Workflows:
                - Workflow Templates Seeding: user-stories/08a-workflow-templates-seeding.md
                - Workflow Authoring & Configuration: user-stories/08b-workflow-authoring-configuration.md
                - Triggers & Approvals: user-stories/08c-triggers-approvals.md
                - Workflow Execution Engine: user-stories/08d-workflow-execution-engine.md
                - Simulation / Dry-Run & Rollback: user-stories/08e-simulation-rollback.md
                - Workflow Observability & Receipts: user-stories/08f-workflow-observability-receipts.md

            - Operations:
                - Decision Making: user-stories/09-decision-audit.md
                - Evidence Export for Regulators: user-stories/09b-evidence-export-regulators.md
                - Monitoring: user-stories/10-observability-monitoring.md
                - Incident Handling: user-stories/10b-incident-handling.md
                - Feedback: user-stories/11-feedback.md

            - Extended Stories:
                - CFO Consumption & Activation: user-stories/12-cfo-consumption-activation.md
                - Ops Connector Failure & Recovery: user-stories/13-ops-connector-failure-recovery.md
                - Hybrid Deployment for Regulated Tenant: user-stories/14-hybrid-deployment.md
                - AI Actor-Assisted Decisioning: user-stories/15-ai-actors-workflows.md
                - Anomaly Engine: user-stories/16-anomaly-engine.md
                - Anomaly Tuning: user-stories/17-anomaly-tuning.md

    - Connectors:
        - Overview: connectors/01-overview.md
        - SAP: connectors/02-sap.md
        - Salesforce: connectors/03-salesforce.md
        - Files & Objects: connectors/04-files-and-objects.md
        - Streams: connectors/05-streams.md
        - Outbound Destinations: connectors/06-outbound-destinations.md
        - Connectors APIs: connectors/07-connector-apis.md

    - Pipeline:
        - Index: pipeline\index.md
        - Overview: pipeline\01-overview.md
        - Ingestion: pipeline\02-ingestion-and-landing.md
        - Raw Store: pipeline\03-raw-stage.md
        - Gold Transform: pipeline\04-gdp-transform.md
        - KPI Materialize: pipeline\05-kpi-materialization.md
        - Orchestration: pipeline\06-orchestration-and-scheduling.md
        - Validation: pipeline\07-data-quality-and-validation.md
        - Evidence: pipeline\08-lineage-and-evidence.md
        - Observability: pipeline\09-observability-slo-and-alerts.md
        - Recovery: pipeline\10-recovery-replay-and-dlq.md
        - Cost Control: pipeline\11-cost-controls-and-scaling.md
        - Configurations: pipeline\12-pipeline-configuration.md
        - Pipeline APIs: pipeline\13-pipeline-apis.md
        - Runners: pipeline\14-runners-and-execution.md
        - Schedulers: pipeline\15-scheduler-options.md
        - Anomaly Detection: pipeline\16-anomaly-integration.md

    - Platform Services:
        - Overview: phs/phs-01-overview.md
        - Infrastructure: phs/phs-02-infrastructure.md
        - Core Architecture: phs/phs-03-core-architecture.md
        - Security & NFRs: phs/phs-04-nfrs.md
        - Storage Strategy: phs/phs-05-storage-strategy.md
        - Storage Residency: phs/phs-06-storage-residency.md
        - Storage Operations: phs/phs-07-storage-operations.md
        - Costs & Budget: phs/phs-08-costs.md
        - Summary: phs/phs-09-summary.md

    - Schema Services:
        - Index: schema/index.md
        - Overview: schema/01-overview.md
        - Schema Contracts: schema/02-schema-contracts.md
        - Schema Enforcement: schema/03-schema-enforcement.md
        - Extraction Schema Model: schema/04-extraction-schema-model.md
        - Raw Schema Model: schema/05-raw-schema-model.md
        - GDP Schema Model: schema/06-gdp-schema-model.md
        - Metric Schema Model: schema/07-metric-schema-model.md
        - Meta Schema Model: schema/08-meta-schema-model.md
        - Schema Database: schema/09-schema-database.md
        - Schema Management: schema/10-schema-management.md

    - KPI Services:
        - Index: kpi/index.md
        - Overview: kpi/01-overview.md
        - Metric Registry: kpi/02-metric-registry.md
        - Metric Catalog: kpi/03-metric-catalog.md
        - Metric APIs: kpi/04-serving-apis.md
        - Job Authoring: kpi/05-job-authoring-and-runtime.md
        - Scheduling: kpi/06-scheduling-and-slo.md
        - Security: kpi/07-security-and-rbac.md
        - Variants: kpi/08-variants-and-lineage.md
        - Observability: kpi/09-observability-and-admin.md
        - Versioning: kpi/10-versioning-and-lifecycle.md
        - Extensions: kpi/11-extensions-and-derivations.md
        - Integrations: kpi/12-anomaly-and-dq-integration.md
        - Outbound Integrations: kpi/13-outbound-integration.md

    - Host App:
        - Overview: host-app/ha-01-overview.md
        - Architecture:
            - Core Architecture: host-app/ha-02-architecture.md
            - Responsibilities & Boundaries: host-app/ha-02a-scope-boundaries.md
            - Identity & RBAC: host-app/ha-02b-identity-rbac.md
            - Contracts Governance: host-app/ha-02c-contracts-governance.md
            - Tenant Management: host-app/ha-02d-tenant-management.md
            - Observability (Read-only Health): host-app/ha-02e-observability.md
            - SLAs & Error Model: host-app/ha-02f-slo-error.md
            - Non-goals & Risks: host-app/ha-02g-nongoals-risks.md
        - Database:
            - Metadata Model (Entities): host-app/ha-03-database.md
            - Reference Data (Calendars/FX/Org): host-app/ha-03a-refdata.md
            - Audit & Evidence: host-app/ha-03b-audit.md
            - Storage & Retention: host-app/ha-03c-storage-retention.md
        - UI:
            - Information Architecture: host-app/ha-04-ia.md
            - Host App UI: host-app/ha-04-ui.md
            - UX Patterns & Accessibility: host-app/ha-04a-ux-accessibility.md
        - Summary: host-app/ha-summary.md

    - Tenant App:
        - Overview: tenant/index.md

        - Foundations:
            - Architecture: tenant/architecture.md
            - Infrastructure: tenant/infrastructure.md
            - Security: tenant/security.md
            - Roles and Permissions: tenant/roles.md

        - Admin Ops:
            - Onboarding Sources: tenant/onboarding-sources.md
            - User Management: tenant/user-management.md
            - Infrastructure Bindings: tenant/infra-bindings.md

        - Delivery and Activation:
            - Health Dashboards: tenant/health.md
            - Requests and Approvals: tenant/requests.md
            - Data Access and Reports: tenant/data.md
            - Activation Panels: tenant/activation.md

        - Developer:
            - API Guide: tenant/api-guide.md
            - API Reference: tenant/api-reference.md

        - Operations:
            - NFRs: tenant/nfr.md
            - Troubleshooting: tenant/troubleshooting.md
            - Release Notes: tenant/release-notes.md

    - KPI Actions:
        - Overview: activation-plane/index.md
        - API Guide: activation-plane/activation-plane-api-guide.md
        - API Reference: activation-plane/activation-plane-api-reference.md
        - Flows: activation-plane/activation-plane-flows.md
        - Examples: activation-plane/activation-plane-examples.md

    - Decisions:
        - Overview: decisions/decisions-overview.md
        - ADR-0001: decisions/ADR-0001.md
        - ADR-0002: decisions/ADR-0002.md
        - ADR-0003: decisions/ADR-0003.md
        - ADR-0004: decisions/ADR-0004.md

    - References:
        - Taxonomy: references/taxonomy.md
        - Glossary: references/glossary.md

extra_css:
  - stylesheets/overrides.css
  # - stylesheets/print-block.css

extra_javascript:
  - javascripts/tablesort.js
