site_name: Enterprise Data Platform
site_description: Technical documentation
copyright: "© 2025 Selenite®  |  Selenite Business Solutions Pvt. Ltd. All rights reserved."

theme:
  name: material
  logo: assets/logos/bare_count_logo_dark.svg
  favicon: assets/logos/bare_count_favicon.png
  features:
    - navigation.instant          # Client-side nav for faster page transitions
    - navigation.tracking         # Update URL anchor as you scroll
    - navigation.tabs             # Top-level sections as tabs
    - navigation.tabs.sticky      # Tabs remain visible on scroll
    - toc.follow                  # Auto-highlight current heading in TOC
    - navigation.top              # “Back to top” button
    - navigation.indexes          # Section landing pages
    - navigation.prune            # Hide empty nav items
    - content.code.copy           # Copy button on code blocks
    - content.action.edit         # “Edit this page” action
    - content.tooltips            # Tooltips via title attributes
    - content.tabs.link           # Linked content tabs across pages
    - search.highlight            # Highlight search matches
    - search.suggest              # Search suggestions

extra:
    generator: false              # drop meta “Made with MkDocs”

markdown_extensions:
  - admonition                     # Callout blocks: note/warning/tip/etc.
  - def_list                       # Definition lists: term + definition syntax
  - footnotes                      # In-page footnotes with backlinks
  - attr_list                      # `{}` attribute lists on elements (ids, classes)
  - md_in_html                     # Allow Markdown inside raw HTML blocks
  - toc:                           # Table of contents
      permalink: false             # Add an anchor link to headings
      toc_depth: 2                 # Limit TOC depth (H2+)
  - pymdownx.details               # `<details>` collapsible sections via `???`
  - pymdownx.superfences:          # Fenced code block superpowers + custom fences
      custom_fences:
        - name: mermaid            # ```mermaid
          class: mermaid           #   graph TD; A-->B
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:            # Pygments-based code highlighting
      linenums: false              # Show line numbers on code blocks
      anchor_linenums: true        # Make line numbers linkable
  - pymdownx.inlinehilite          # `==inline code==` highlighting shorthand
  - pymdownx.tabbed:               # Content tabs: ```tab=Foo
      alternate_style: true        # Use alt styling that fits Material nicely
  - pymdownx.tasklist:             # [ ] and [x] task lists
      custom_checkbox: true        # Styled checkboxes
      clickable_checkbox: true     # Toggle checkboxes in the browser
  - pymdownx.critic                # Critic markup (add/del/sub comments) for reviews
  - pymdownx.smartsymbols          # Converts (c), (tm), --, ... into proper glyphs
  - pymdownx.emoji:                # :emoji: support using Material’s SVG set
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:             # Reuse content via !INCLUDE or snippet syntax
      base_path: docs              # Root path for included snippets
  - pymdownx.magiclink             # Auto-link bare URLs and @user/#issue patterns
  - pymdownx.betterem              # Smarter emphasis handling (edge-case fixes)
  - pymdownx.caret                 # ^^insertions^^ (caret markup)
  - pymdownx.mark                  # ==highlights== (mark markup)
  - pymdownx.tilde                 # ~~subscripts~~ and ~~deletions~~ (tilde markup)

plugins:
  - search                         # Built-in search index
  - minify:                        # Reduce HTML size
      minify_html: true
  - redirects                      # Maintain old → new URL mappings
  - awesome-pages                  # Folder-based nav ordering via .pages files

nav:
    - Home:
        - Index: index.md

    - About Platform:
        - Index: about-platform/index.md
        - Problem: about-platform/01-problem.md
        - Root Causes: about-platform/02-root-causes.md
        - Solution: about-platform/03-solution.md
        - Modules: about-platform/04-platform-modules.md
        - Working: about-platform/05-platform-working.md
        - Offerings: about-platform/06-offerings.md
        - Deployment: about-platform/07-deployment.md

        - User Stories:
            - Index: user-stories/index.md
            - User Roles: user-stories/user-roles.md

            - Setting up Platform:
                - Infra Deployment: user-stories/00a-platform-infrastructure-deployment.md
                - Connector Deployment: user-stories/00b-connector-deployment.md
                - Schema Seeding: user-stories/00c-schema-templates-seeding.md
                - Access Baseline: user-stories/00d-access-rbac-baseline.md

            - Managing Tenant:
                - Tenant Provisioning: user-stories/01-tenant-provisioning.md
                - Tenant Infrastructure Provisioning: user-stories/01b-tenant-infrastructure-provisioning.md
                - Tenant Decommissioning / Offboarding: user-stories/01c-tenant-decommissioning.md

            - Onboarding Data:
                - Data Source Onboarding: user-stories/02-source-onboarding.md
                - Connector Handshake & Preflight: user-stories/02b-connector-handshake-preflight.md

            - Governance:
                - Setting Up Guardrails: user-stories/04-guardrails-dqc.md
                - Evidence: user-stories/05-evidence-lineage.md
                - Automated Housekeeping & Cost Controls: user-stories/05b-housekeeping-cost-controls.md

            - Managing Schemas:
                - Source (Raw) Schema Lifecycle: user-stories/03a-raw-schema-lifecycle.md
                - GDP Schema Lifecycle: user-stories/03b-gdp-schema-lifecycle.md
                - KPI Schema Lifecycle: user-stories/03c-kpi-schema-lifecycle.md
                - Tenant Schema Change Request: user-stories/03d-tenant-schema-change-request.md
                - Tenant-Specific Schema Extension: user-stories/03e-tenant-specific-schema-extension.md
                - Safe Rollout & Rollback: user-stories/03f-safe-rollout-rollback.md
                - Impact Analysis & Notifications: user-stories/03g-impact-analysis-notifications.md

            - KPI Lifecycle:
                - KPI Publishing: user-stories/06-kpi-publishing.md
                - KPI Consumption: user-stories/07-kpi-consumption.md

            - Data Action Workflows:
                - Workflow Templates Seeding: user-stories/08a-workflow-templates-seeding.md
                - Workflow Authoring & Configuration: user-stories/08b-workflow-authoring-configuration.md
                - Triggers & Approvals: user-stories/08c-triggers-approvals.md
                - Workflow Execution Engine: user-stories/08d-workflow-execution-engine.md
                - Simulation / Dry-Run & Rollback: user-stories/08e-simulation-rollback.md
                - Workflow Observability & Receipts: user-stories/08f-workflow-observability-receipts.md

            - Operations:
                - Decision Making: user-stories/09-decision-audit.md
                - Evidence Export for Regulators: user-stories/09b-evidence-export-regulators.md
                - Monitoring: user-stories/10-observability-monitoring.md
                - Incident Handling: user-stories/10b-incident-handling.md
                - Feedback: user-stories/11-feedback.md

            - Extended Stories:
                - CFO Consumption & Activation: user-stories/12-cfo-consumption-activation.md
                - Ops Connector Failure & Recovery: user-stories/13-ops-connector-failure-recovery.md
                - Hybrid Deployment for Regulated Tenant: user-stories/14-hybrid-deployment.md
                - AI Actor-Assisted Decisioning: user-stories/15-ai-actors-workflows.md
                - Anomaly Engine: user-stories/16-anomaly-engine.md
                - Anomaly Tuning: user-stories/17-anomaly-tuning.md

    - Modules:
        - Index: modules/index.md

        - Host Modules:
            - Overview: modules/host/index.md

            - Policy Registry:
              - Index: modules/host/policy-registry/index.md
              - Data Model: modules/host/policy-registry/data-model.md
              - User Interface: modules/host/policy-registry/ui.md
              - API: modules/host/policy-registry/api.md
              - Observability: modules/host/policy-registry/observability.md
              - Runbook: modules/host/policy-registry/runbook.md
              - Security: modules/host/policy-registry/security.md

            - Data Contract Registry:
              - Index: modules/host/data-contract-registry/index.md
              - Data Model: modules/host/data-contract-registry/data-model.md
              - User Interface: modules/host/data-contract-registry/ui.md
              - API: modules/host/data-contract-registry/api.md
              - Observability: modules/host/data-contract-registry/observability.md
              - Runbook: modules/host/data-contract-registry/runbook.md
              - Security: modules/host/data-contract-registry/security.md

            - Tenant Management: modules/host/tenant-management/index.md
            - Lineage Obligations: modules/host/lineage-obligations/index.md

        - Compute Modules:
            - Overview: modules/compute/index.md
            - Ingestion: modules/compute/ingestion/index.md
            - Normalization: modules/compute/normalization/index.md
            - KPI Build: modules/compute/kpi-build/index.md
            - Publish: modules/compute/publish/index.md
            - Orchestration: modules/compute/orchestration/index.md

        - Data Storage Modules:
            - Overview: modules/storage/index.md
            - Raw Store: modules/storage/raw-store/index.md
            - GDP Store: modules/storage/gdp-store/index.md
            - KPI Store: modules/storage/kpi-store/index.md
            - Published Store: modules/storage/published-store/index.md
            - Calendar: modules/storage/gdp-calendar/index.md

        - Consumption Modules:
            - Overview: modules/consumption/index.md
            - Activation APIs: modules/consumption/activation-apis/index.md
            - Exports: modules/consumption/exports/index.md
            - Webhooks: modules/consumption/webhooks/index.md
            - Catalog: modules/consumption/catalog/index.md

        - Action Modules:
            - Overview: modules/action/index.md
            - Action Engine: modules/action/action-engine/index.md
            - Action Catalog: modules/action/action-catalog/index.md
            - Action Delivery: modules/action/action-delivery/index.md

        - Security Modules:
            - Overview: modules/security/index.md
            - Gateway: modules/security/gateway/index.md
            - Network Security: modules/security/network-security/index.md

        - Access Modules:
            - Overview: modules/access/index.md
            - Authentication: modules/access/authentication/index.md
            - Authorization: modules/access/authorization/index.md
            - Subscription Enforcement: modules/access/subscription-enforcement/index.md

        - Trust Modules:
            - Overview: modules/trust/index.md
            - Evidence Ledger: modules/trust/evidence-ledger/index.md
            - Secrets: modules/trust/secrets/index.md
            - Encryption: modules/trust/encryption/index.md

        - Runtime Modules:
            - Overview: modules/runtime/index.md
            - Scheduler: modules/runtime/scheduler/index.md
            - Messaging and Events: modules/runtime/messaging-events/index.md
            - Observability: modules/runtime/observability/index.md
            - Error Handling: modules/runtime/error-handling/index.md
            - Metering: modules/runtime/metering/index.md

        - Data Utilities Modules:
            - Index: modules/utilities/index.md
            - Schema Registry: modules/utilities/schema-registry/index.md
            - Catalog and Discovery: modules/utilities/catalog-discovery/index.md
            - Data Observability: modules/utilities/data-observability/index.md
            - Migration Service: modules/utilities/migration-service/index.md

    - Architecture:
        - Principles: architecture/principles.md
        - Logical Stack: architecture/logical-stack.md
        - Data Flows: architecture/data-flows.md
        - Governance: architecture/governance.md
        - ADRs: architecture/adrs.md

    - Infrastructure:
        - Deployment Topologies: infrastructure/deployment-topologies.md
        - Cloud Reference: infrastructure/cloud-reference.md
        - CI/CD & Packaging: infrastructure/ci-cd.md
        - Monitoring & SLOs: infrastructure/monitoring-slos.md
        - Security Baselines: infrastructure/security-baselines.md

    - Admin App:
        - Overview: applications/admin-app/index.md
        - Setup: applications/admin-app/setup.md
        - Features: applications/admin-app/features.md
        - Roles & Permissions: applications/admin-app/roles-permissions.md
        - Configuration: applications/admin-app/configuration.md
        - Troubleshooting: applications/admin-app/troubleshooting.md
        - Changelog: applications/admin-app/changelog.md

    - Customer App:
        - Overview: applications/customer-app/index.md
        - Getting Started: applications/customer-app/getting-started.md
        - Features: applications/customer-app/features.md
        - Self Service: applications/customer-app/self-service.md
        - Configuration: applications/customer-app/configuration.md
        - Troubleshooting: applications/customer-app/troubleshooting.md
        - Changelog: applications/customer-app/changelog.md

    - Engineering:
        - Index: engineering/index.md
        - Local Development: engineering/local-development.md
        - Build & Release: engineering/build-release.md
        - CI/CD: engineering/cicd.md
        - Best Practices: engineering/best-practices.md
        - Roadmap: engineering/roadmap.md
        - Infrastructure: engineering/infrastructure.md
        - Testing & Quality: engineering/testing-quality.md
        - Starter Kits: engineering/starter-kits.md
        - Runbooks:
            - Index: engineering/runbooks/index.md

    - References:
        - Decisions:
            - Overview: decisions/decisions-overview.md
            - ADR-0001: decisions/ADR-0001.md
            - ADR-0002: decisions/ADR-0002.md
            - ADR-0003: decisions/ADR-0003.md
            - ADR-0004: decisions/ADR-0004.md
        - Taxonomy: references/taxonomy.md
        - Glossary: references/glossary.md
        - Writing Guides:
            - Documents Writing Guide: references/writing-guides/documents-writing-guide.md
            - Modules Writing Guide: references/writing-guides/modules-writing-guide.md
            - API Writing Guide: references/writing-guides/api-writing-guide.md
        - Dependency Guard: references/dependency-guard.md
        - Gaps/Open Issues: references/gaps-open-issues.md
        - Pending Actions: references/pending-actions.md


extra_css:
  - stylesheets/overrides.css
  # - stylesheets/print-block.css

extra_javascript:
  - javascripts/tablesort.js
