site_name: Data Platform Documentation
site_description: Technical documentation
copyright: "© 2025 Selenite®  |  Selenite Business Solutions Pvt. Ltd. All rights reserved."

theme:
  name: material
  logo: assets/logos/bare_count_logo_dark.svg  # Logo in the light scheme
  favicon: assets/logos/bare_count_favicon.png
  features:
    - navigation.instant          # Client-side nav for faster page transitions
    - navigation.tracking         # Update URL anchor as you scroll
    - navigation.tabs             # Top-level sections as tabs
    - navigation.tabs.sticky      # Tabs remain visible on scroll
    - toc.follow                  # Auto-highlight current heading in TOC
    - navigation.top              # “Back to top” button
    - navigation.indexes          # Section landing pages
    - navigation.prune            # Hide empty nav items
    - content.code.copy           # Copy button on code blocks
    - content.action.edit         # “Edit this page” action
    - content.tooltips            # Tooltips via title attributes
    - content.tabs.link           # Linked content tabs across pages
    - search.highlight            # Highlight search matches
    - search.suggest              # Search suggestions

extra:
    generator: false              # drop meta “Made with MkDocs”

markdown_extensions:
  - admonition                     # Callout blocks: note/warning/tip/etc.
  - def_list                       # Definition lists: term + definition syntax
  - footnotes                      # In-page footnotes with backlinks
  - attr_list                      # `{}` attribute lists on elements (ids, classes)
  - md_in_html                     # Allow Markdown inside raw HTML blocks
  - toc:                           # Table of contents
      permalink: false             # Add an anchor link to headings
      toc_depth: 2                 # Limit TOC depth (H2+)
  - pymdownx.details               # `<details>` collapsible sections via `???`
  - pymdownx.superfences:          # Fenced code block superpowers + custom fences
      custom_fences:
        - name: mermaid            # ```mermaid
          class: mermaid           #   graph TD; A-->B
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:            # Pygments-based code highlighting
      linenums: true               # Show line numbers on code blocks
      anchor_linenums: true        # Make line numbers linkable
  - pymdownx.inlinehilite          # `==inline code==` highlighting shorthand
  - pymdownx.tabbed:               # Content tabs: ```tab=Foo
      alternate_style: true        # Use alt styling that fits Material nicely
  - pymdownx.tasklist:             # [ ] and [x] task lists
      custom_checkbox: true        # Styled checkboxes
      clickable_checkbox: true     # Toggle checkboxes in the browser
  - pymdownx.critic                # Critic markup (add/del/sub comments) for reviews
  - pymdownx.smartsymbols          # Converts (c), (tm), --, ... into proper glyphs
  - pymdownx.emoji:                # :emoji: support using Material’s SVG set
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:             # Reuse content via !INCLUDE or snippet syntax
      base_path: docs              # Root path for included snippets
  - pymdownx.magiclink             # Auto-link bare URLs and @user/#issue patterns
  - pymdownx.betterem              # Smarter emphasis handling (edge-case fixes)
  - pymdownx.caret                 # ^^insertions^^ (caret markup)
  - pymdownx.mark                  # ==highlights== (mark markup)
  - pymdownx.tilde                 # ~~subscripts~~ and ~~deletions~~ (tilde markup)

plugins:
  - search                         # Built-in search index
  - minify:                        # Reduce HTML size
      minify_html: true
  - redirects                      # Maintain old → new URL mappings
  - awesome-pages                  # Folder-based nav ordering via .pages files
  - git-revision-date-localized:   # Page dates from Git history
      enable_creation_date: false

nav:
    - Home:
        - Overview: index.md

        - About Platform:
            - Overview: about-platform/00-overview.md
            - The Problem: about-platform/01-problem.md
            - Root Causes: about-platform/02-root-causes.md
            - The Idea: about-platform/03-idea.md
            - The Solution: about-platform/04-solution.md
            - Benefits: about-platform/05-benefits.md
            - Offering: about-platform/06-offering.md
            - Proof of Value: about-platform/07-proof-of-value.md
            - Positioning: about-platform/08-positioning.md

        - User Stories:
            - Overview: user-stories/user-stories-overview.md

        - Brand Guide:
            - Introduction: brand-guide/brand-introduction.md
            - MkDocs Theme: assets/document-styles/mkdocs-guide.md

    - Platform Services:
        - Overview: phs/phs-01-overview.md
        - Infrastructure: phs/phs-02-infrastructure.md
        - Core Architecture: phs/phs-03-core-architecture.md
        - Security & NFRs: phs/phs-04-nfrs.md
        - Storage Strategy: phs/phs-05-storage-strategy.md
        - Storage Residency: phs/phs-06-storage-residency.md
        - Storage Operations: phs/phs-07-storage-operations.md
        - Costs & Budget: phs/phs-08-costs.md

    - Schema Services:
        - Overview: schema/index.md
        - GDP Framework: schema/gdp-framework.md
        - Contracts & Versioning: schema/contracts.md
        - Enforcement & Validation: schema/enforcement.md

    - KPI Services:
        - Overview: kpi/index.md
        - KPI Framework: kpi/framework.md
        - Validation & Thresholds: kpi/validation.md

    - APIs:
        - Guides:
            - Overview: apis/guides/index.md
            - Auth & Scopes: apis/guides/auth.md
            - Versioning & Deprecation: apis/guides/versioning.md
            - Errors & Retries: apis/guides/errors.md
            - Rate Limits & Quotas: apis/guides/rate-limits.md
            - Webhooks & Events: apis/guides/events.md
            - Examples:
                - CICD → PHS (CLI/SDK): apis/guides/examples-cicd-phs.md
                - Contract Publish (Admin App → PHS): apis/guides/examples-contracts.md
                - Connector Egress (Raw): apis/guides/examples-egress.md
        - Reference:
            - PHS API (OpenAPI): apis/reference/phs-openapi.md
            - Schema Services API (OpenAPI): apis/reference/schema-openapi.md
            - KPI Services API (OpenAPI): apis/reference/kpi-openapi.md
            - Admin Host App API (OpenAPI): apis/reference/paa-openapi.md
            - Tenant App API (OpenAPI): apis/reference/tenant-openapi.md

    - Host App:
        - Overview: pha/index.md
        - Tenant Management: pha/tenant.md
        - Contract Lifecycle: pha/contracts.md

    - Tenant App:
        - Overview: tenant/index.md
        - Tenant Infrastructure: tenant/infrastructure.md
        - Onboarding: tenant/onboarding.md
        - Data Access & Reports: tenant/data.md

    - Decisions:
        - Overview: decisions/decisions-overview.md

    - Glossary: glossary/glossary.md

extra_css:
  - stylesheets/overrides.css
  - stylesheets/print-block.css

extra_javascript:
  - javascripts/tablesort.js
